# Tracking the Student Lifecycle {#student-tracking}

#### Keywords

continuing education, customer tracking, student lifecycle tracking, student outcomes

## Surveys on surveys.

I work in professional and continuing education. We lack insight on our student lifecycle as a whole. How can we best serve our students when we do not see their experience from beginning to end? Currently, the organization surveys our students at key points throughout their time with us: at application, enrollment, as students through course evaluations, at graduation and as alumni. But we produce individual, static reports for each of these surveys for 100+ programs. We have no way to synthesize this data and use it productively for the benefit of our students. 

We have all of this data, from surveys, our databases, vendors, sources such as Career Bridge and LinkedIn, and our CRM, but we are not using this information to its fullest extent. By producing static, PDF reports, we miss key information that would enable us to further improve our programs and the student experience. Improving our data management processes would enable us to improve our student experience.

## Tracking the student lifecycle.

Currently, we have access to a significant amount of unlinked data from multiple sources and are collecting more all the time. With some careful adjustments, we can link these surveys with our databases and to our vendor data. Each student has a unique, randomly generated ID associated with them in the databases. I propose we include this when we gather the sample lists for our surveys and embed it in the survey data, like we already do with demographic information. When we pull data from our databases, we can include this identifier, then link database data with survey responses. Vendor data is typically already linked to our databases via email and we could extend the use of the identifer there as well. In addition, by using this randomly generated number when we pull data for our reports, we can link individuals while still excluding identifying information such as names and emails.

Once we have this data linked, we can begin writing interactive reports using tools such as Tableau or Vocalize. We can incorporate improved analysis on open ended questions using word clouds and sentiment anaylsis. We can finally view trends over time, all in one place, instead of bringing up PDF reports for each year. We can compare programs to their sectors. We can follow one cohort through their entire experience with us: enrollment surveys, course evaluations, exit surveys and alumni surveys, not to mention other data we can collect from our vendor sources. Program managers will have more freedom to explore their data, thus making more informed decision about their programs. We can easily see which programs are struggling, when they started struggling, and from there we can make changes to improve them.

## Better serve our community.

Using the lifecycle data, we can better see how we are serving our students: from application feedback to program satisfaction and job outcomes. We would have this data all in one, accessible place. Comparisons over time, across programs in a given sector, and identifying changes in cohort opinions and attitudes from beginning to end would give us new insights that we've never had access to before. We will make more informed decisions better rooted in our data and more easily identify fixable issues to improve the student experience. 

This is by no means perfect. Not everyone will respond to our surveys and we will have gaps in our data. There are privacy concerns. Even if we use a randomly generated number, it is still associated with identifying information in at least one database. Currently we manage privacy concerns through only allowing access through certain departments, who remove identifying information before handing it off. We can use a similar process to mitigate these privacy concerns. Our surveys are confidential, but not anonymous, and we already have processes in place for handling privacy there. Despite the risks, improving our data processes would give us a more holistic view of our students and their experience, and that information will allow us to better serve our students and community.
